archiver-user:
    username: alidron_archiver
    password: jk5IwyRdtRgE5HwIfrSByW40I
    hostname: env['DB_PORT_8086_TCP_ADDR']
    port: env['DB_PORT_8086_TCP_PORT']
    db: alidron-test
    scheme: influxdb

admin-user:
    username: root
    password: root
    hostname: env['DB_PORT_8086_TCP_ADDR']
    port: env['DB_PORT_8086_TCP_PORT']
    scheme: influxdb

buffer:
    path: /data/buffer.pkl
