archiver-user:
    username: alidron_archiver_user
    password: password
    hostname: env['DB_PORT_8086_TCP_ADDR']
    port: env['DB_PORT_8086_TCP_PORT']
    db: alidron_data
    scheme: influxdb

admin-user:
    username: root
    password: root
    hostname: env['DB_PORT_8086_TCP_ADDR']
    port: env['DB_PORT_8086_TCP_PORT']
    scheme: influxdb

buffer:
    path: /data/buffer.pkl

config:
    default_precision: ms
    default_smoothing: False
