FROM alidron/rpi-alidron-isac
MAINTAINER Axel Voitier <axel.voitier@gmail.com>

WORKDIR /app/alidron-archiver
COPY requirements.txt /app/alidron-archiver/
RUN pip install -r requirements.txt \
 && rm -rf /root/.cache/pip   

COPY . /app/alidron-archiver
